#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

# actions to do
my $event = 'nethserver-fail2ban-update';
event_actions($event, 
             'initialize-default-databases' => '00');

#templates to expand
foreach my $event (qw ( nethserver-fail2ban-update nethserver-fail2ban-save)) {
    templates2events("/etc/fail2ban/fail2ban.local", $event);
    templates2events('/etc/fail2ban/jail.local', $event);
}

# services to launch on event
foreach my $event (qw ( nethserver-fail2ban-update nethserver-fail2ban-save)) {
event_services($event,
    'fail2ban'=> 'restart');
}
