#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

# actions to do
my $event = 'nethserver-fail2ban-update';
event_actions($event,
             'initialize-default-databases' => '00');
templates2events("/etc/fail2ban/fail2ban.local", $event);
templates2events('/etc/fail2ban/action.d/sendmail-common.local', $event);
templates2events('/etc/sudoers', $event);

# nethserver-firewall-base-save
my $event = 'nethserver-firewall-base-save';
templates2events('/etc/fail2ban/jail.local', $event);
templates2events('/etc/shorewall/initdone', $event);
templates2events('/etc/shorewall/blrules', $event);

#Action to unbanIP
my $event = 'nethserver-fail2banUnBan-save';
event_actions($event, 'fail2ban-unban' => '10');

# nethserver-fail2ban-save -> we need to expand/restart shorewall
my $event = 'nethserver-fail2ban-save';
event_actions($event,
    'nethserver-fail2ban-unban-whitelist' => '10',
    'nethserver-fail2ban-shorewall-event' => '90');
templates2events('/etc/fail2ban/action.d/sendmail-common.local', $event);

# Fail2ban services restart
foreach my $event (qw ( nethserver-firewall-base-save )) {
    event_services($event,'fail2ban'=> 'restart');
}
