#!/bin/bash

#
# Build  NS7 UI
#

set -e

# Build UI
NODE_OPTIONS="--openssl-legacy-provider"
export NODE_OPTIONS
pushd ui
npm install
npm run build
popd

tar -C ui/dist -c -z -f nethserver-fail2ban-cockpit.tar.gz .
