#!/bin/bash
#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Do a vacuum of the sqlite database of fail2ban each month
# Test first if the db is not locked, else try 5 times.
#

for (( i=1; i<=5; i++ ))
do
    COMMAND=$(/usr/bin/sqlite3 /var/lib/fail2ban/fail2ban.sqlite3 "BEGIN EXCLUSIVE;COMMIT;" > /dev/null 2>&1 )
    if [[ $? -eq 0 ]]; then
        /usr/bin/sqlite3 /var/lib/fail2ban/fail2ban.sqlite3 "VACUUM;"
        exit $?
    else
        sleep 5
    fi
done
