#!/usr/bin/perl
#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Display all IP currently banned in all f2b-* sets of ipset

sub uniq {
  my %seen;
  return grep { !$seen{$_}++ } @_;
}

my @IP = ();
my $IP = '';

foreach my $set (split ("\n", `ipset -L -name`)) {
    next if ($set !~ m/^f2b-/);
    $IP .= `ipset -L $set -exist| grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}"`;
}

foreach my $i (uniq (split ("\n", $IP))){
    print $i."\n";
}
