#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

binmode STDOUT, ":utf8";
use utf8;

my $jsonFile = '/var/lib/nethserver/fail2ban/fail2ban.json';
my $json;

# create file if not exists
if (! -f $jsonFile) {
    system("/usr/libexec/nethserver/fail2ban-statistics");
}

open my $fh, "<", $jsonFile;
$json = <$fh>;
close $fh;

print $json;
