#!/bin/bash
#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

IP=$2
if [[ $IP == '' ]]; then 
    exit 0
fi

#Retrieve the jail list
JAILS=$(fail2ban-client status | grep " Jail list:" | sed 's/`- Jail list://g' | sed 's/,//g')

for j in $JAILS
do
    /usr/bin/fail2ban-client set $j unbanip $IP 2> /dev/null
done

# retrieve the set of ipset, then unban the ip in all set
SET=$(ipset -L -name)
for s in $SET
do
    ipset del $s $IP -exist > /dev/null
done
